workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

stages:
  - deploy

variables:
  GIT_STRATEGY: fetch

deploy_project:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR

    # deploy using docker compose
    - docker compose up -d --build
