stages:
  - deploy

variables:
  GIT_STRATEGY: fetch

deploy_project:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR

    # add gitlab secrets to env so it is accessible by docker
    # - echo "DB_UPDATE=$DB_UPDATE" > .env

    # - echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" >> .env
    # - echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> .env
    # - echo "MYSQL_USER=$MYSQL_USER" >> .env
    # - echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
    # - echo "DB_URL=$DB_URL" >> .env

    # - echo "CERTBOT_EMAIL=$CERTBOT_EMAIL" >> .env
    # - echo $DB_URL

    # deploy using docker compose
    - docker compose up -d --no-cache
