services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - static:/var/www

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --non-interactive --email ${CERTBOT_EMAIL} -d gosmartlib.tech --agree-tos

  db:
    image: mysql:9.6.0
    container_name: db
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306

  backend:
    depends_on:
      - db
    container_name: backend
    volumes:
      - maven-repo:/root/.m2
      - static:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_UPDATE: ${DB_UPDATE}
      DB_URL: ${DB_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_DIR: ${UPLOAD_DIR}
      COOKIE_SECURE: ${COOKIE_SECURE}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      BOOKS_KEY: ${BOOKS_KEY}
    build:
      context: ./backend
      dockerfile: Dockerfile

volumes:
  certbot:
    name: certbot
    external: true
  certbot_www:
    name: certbot_www
    external: true
  maven-repo:
    name: maven-repo
    external: true
  static:
    name: static
    external: true
