server {
    server_tokens off;
    etag off;
    listen 80;

    location ~ "^/static/file/(?<id>[a-f0-9]{32})/(?<filename>[^/]+)$" {

        alias /mnt/c/Users/<windows user>/<location to dir>/static/file/$id;

        add_header Content-Disposition "attachment; filename=\"$filename\"";
    }

    location /static/ {
        add_header    Last-Modified '';
        add_header Vary "";
        add_header Cache-Control "public, max-age=31536000, immutable";

        alias /mnt/c/Users/<windows user>/<location to dir>/static/;
    }
}