spring.application.name=backend
server.servlet.context-path=/api
spring.jackson.property-naming-strategy=SNAKE_CASE

# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${DB_UPDATE}
spring.jpa.show-sql=true

# session cookie security (SameSite=Strict compensates for disabled CSRF tokens)
spring.session.jdbc.initialize-schema=always
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=${COOKIE_SECURE}
server.servlet.session.cookie.max-age=30d
server.servlet.session.timeout=30d
server.servlet.session.cookie.name=session


# file upload (bigger size filesize too large blocked at nginx)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# custom properties
app.upload-dir=${UPLOAD_DIR}
app.bcrypt-rounds=12
app.google-books.api-key=${BOOKS_KEY}

# smartschool oauth
app.smartschool.client-id=${CLIENT_ID}
app.smartschool.client-secret=${CLIENT_SECRET}
app.smartschool.callback=https://gosmartlib.tech/api/oauth


logging.level.org.springframework.security=DEBUG